version: '3.3'

services:
  bot:
    restart: always
    build:
      context: main
    volumes:
      - /main:/main
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres_data: