"""empty message

Revision ID: cbbaba76fdc3
Revises: db84eaf7a0ef
Create Date: 2021-09-26 18:03:27.741686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbaba76fdc3'
down_revision = 'db84eaf7a0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'key', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'key', type_='unique')
    # ### end Alembic commands ###
