"""empty message

Revision ID: db84eaf7a0ef
Revises: 3bcc65e467d5
Create Date: 2021-09-26 14:36:44.305934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db84eaf7a0ef'
down_revision = '3bcc65e467d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('key_user_id_fkey', 'key', type_='foreignkey')
    op.create_foreign_key(None, 'key', 'user', ['user_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'key', type_='foreignkey')
    op.create_foreign_key('key_user_id_fkey', 'key', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
